filter:
    excluded_paths: 
      - vendor/*
      - tests/*
      - Tests/*
      - app/*
      - bin/*
      - library/*
      - contrib/*
      - typo3/contrib/*
      - typo3/sysext/adodb/*
      - typo3/sysext/openid/lib/*
      - typo3/sysext/core/Tests/*
      - typo3/sysext/backend/Tests/*
      - typo3/sysext/frontend/Tests/*
      - typo3/sysext/belog/Tests/*
      - typo3/sysext/beuser/Tests/*
      - typo3/sysext/documentation/Tests/*
      - typo3/sysext/extbase/Tests/*
      - typo3/sysext/extensionmanager/Tests/*
      - typo3/sysext/felogin/Tests/*
      - typo3/sysext/fluid/Tests/*
      - typo3/sysext/form/Tests/*
      - typo3/sysext/indexed_search/Tests/*
      - typo3/sysext/install/Tests/*
      - typo3/sysext/lang/Tests/*
      - typo3/sysext/lowlevel/Tests/*
      - typo3/sysext/recordlist/Tests/*
      - typo3/sysext/reports/Tests/*
      - typo3/sysext/saltedpasswords/Tests/*
      - typo3/sysext/scheduler/Tests/*

tools:
    php_loc:
        enabled: false
        excluded_dirs: [vendor/*, tests/*, Tests/*, app/*, bin/*, library/*, contrib/*, typo3/contrib/*, typo3/sysext/adodb/*, typo3/sysext/openid/lib/*, typo3/sysext/core/Tests/*, typo3/sysext/backend/Tests/*, typo3/sysext/frontend/Tests/*, typo3/sysext/belog/Tests/*, typo3/sysext/beuser/Tests/*, typo3/sysext/documentation/Tests/*, typo3/sysext/extbase/Tests/*, typo3/sysext/extensionmanager/Tests/*, typo3/sysext/felogin/Tests/*, typo3/sysext/fluid/Tests/*, typo3/sysext/form/Tests/*, typo3/sysext/indexed_search/Tests/*, typo3/sysext/install/Tests/*, typo3/sysext/lang/Tests/*, typo3/sysext/lowlevel/Tests/*, typo3/sysext/recordlist/Tests/*, typo3/sysext/reports/Tests/*, typo3/sysext/saltedpasswords/Tests/*, typo3/sysext/scheduler/Tests/*]

    php_mess_detector:
        enabled: false
        filter:
            excluded_paths: [vendor/*, tests/*, Tests/*, app/*, bin/*, library/*, contrib/*, typo3/contrib/*, typo3/sysext/adodb/*, typo3/sysext/openid/lib/*, typo3/sysext/core/Tests/*, typo3/sysext/backend/Tests/*, typo3/sysext/frontend/Tests/*, typo3/sysext/belog/Tests/*, typo3/sysext/beuser/Tests/*, typo3/sysext/documentation/Tests/*, typo3/sysext/extbase/Tests/*, typo3/sysext/extensionmanager/Tests/*, typo3/sysext/felogin/Tests/*, typo3/sysext/fluid/Tests/*, typo3/sysext/form/Tests/*, typo3/sysext/indexed_search/Tests/*, typo3/sysext/install/Tests/*, typo3/sysext/lang/Tests/*, typo3/sysext/lowlevel/Tests/*, typo3/sysext/recordlist/Tests/*, typo3/sysext/reports/Tests/*, typo3/sysext/saltedpasswords/Tests/*, typo3/sysext/scheduler/Tests/*]
        config:
            code_size_rules: { cyclomatic_complexity: true, npath_complexity: true, excessive_method_length: true, excessive_class_length: true, excessive_parameter_list: true, excessive_public_count: true, too_many_fields: true, too_many_methods: true, excessive_class_complexity: true }
            design_rules: { number_of_class_children: true, depth_of_inheritance: true, coupling_between_objects: true }
            unused_code_rules: { unused_local_variable: true, unused_private_method: true, unused_formal_parameter: true }
            naming_rules: { boolean_method_name: true }
            controversial_rules: { camel_case_class_name: true, camel_case_property_name: true, camel_case_method_name: true, camel_case_parameter_name: true, camel_case_variable_name: true }

    php_analyzer:
        enabled: false
        filter:
            excluded_paths: [vendor/*, tests/*, Tests/*, app/*, bin/*, library/*, contrib/*, typo3/contrib/*, typo3/sysext/adodb/*]

    php_cpd:
        enabled: false
        excluded_dirs: [vendor/*, tests/*, Tests/*, app/*, bin/*, library/*, contrib/*, typo3/contrib/*, typo3/sysext/adodb/*, Tests]

    php_code_sniffer:
        enabled: true
        filter:
            excluded_paths: [vendor/*, tests/*, Tests/*, app/*, bin/*, library/*, contrib/*, typo3/contrib/*, typo3/sysext/adodb/*, typo3/sysext/openid/lib/*, typo3/sysext/core/Tests/*, typo3/sysext/backend/Tests/*, typo3/sysext/frontend/Tests/*, typo3/sysext/belog/Tests/*, typo3/sysext/beuser/Tests/*, typo3/sysext/documentation/Tests/*, typo3/sysext/extbase/Tests/*, typo3/sysext/extensionmanager/Tests/*, typo3/sysext/felogin/Tests/*, typo3/sysext/fluid/Tests/*, typo3/sysext/form/Tests/*, typo3/sysext/indexed_search/Tests/*, typo3/sysext/install/Tests/*, typo3/sysext/lang/Tests/*, typo3/sysext/lowlevel/Tests/*, typo3/sysext/recordlist/Tests/*, typo3/sysext/reports/Tests/*, typo3/sysext/saltedpasswords/Tests/*, typo3/sysext/scheduler/Tests/*]
        config:
            standard: TYPO3CMS

    external_code_coverage:
        enabled: true
        timeout: '1800'