filter:
    excluded_paths: 
      - vendor/*
      - tests/*
      - Tests/*
      - app/*
      - bin/*
      - library/*
      - contrib/*
      - typo3/contrib/*
      - typo3/sysext/adodb/*
      - typo3/sysext/openid/lib/*
      - typo3/sysext/core/Tests/*
      - typo3/sysext/backend/Tests/*
      - typo3/sysext/frontend/Tests/*
      - typo3/sysext/belog/Tests/*
      - typo3/sysext/beuser/Tests/*
      - typo3/sysext/documentation/Tests/*
      - typo3/sysext/extbase/Tests/*
      - typo3/sysext/extensionmanager/Tests/*
      - typo3/sysext/felogin/Tests/*
      - typo3/sysext/fluid/Tests/*
      - typo3/sysext/form/Tests/*
      - typo3/sysext/indexed_search/Tests/*
      - typo3/sysext/install/Tests/*
      - typo3/sysext/lang/Tests/*
      - typo3/sysext/lowlevel/Tests/*
      - typo3/sysext/recordlist/Tests/*
      - typo3/sysext/reports/Tests/*
      - typo3/sysext/saltedpasswords/Tests/*
      - typo3/sysext/scheduler/Tests/*
      - typo3/sysext/impexp/Tests/*
      - typo3/sysext/workspaces/Tests/*

tools:
    php_loc:
        enabled: true
        excluded_dirs: [vendor/*, tests/*, Tests/*, app/*, bin/*, library/*, contrib/*, typo3/contrib/*, typo3/sysext/adodb/*, typo3/sysext/openid/lib/*, typo3/sysext/core/Tests/*, typo3/sysext/backend/Tests/*, typo3/sysext/frontend/Tests/*, typo3/sysext/belog/Tests/*, typo3/sysext/beuser/Tests/*, typo3/sysext/documentation/Tests/*, typo3/sysext/extbase/Tests/*, typo3/sysext/extensionmanager/Tests/*, typo3/sysext/felogin/Tests/*, typo3/sysext/fluid/Tests/*, typo3/sysext/form/Tests/*, typo3/sysext/indexed_search/Tests/*, typo3/sysext/install/Tests/*, typo3/sysext/lang/Tests/*, typo3/sysext/lowlevel/Tests/*, typo3/sysext/recordlist/Tests/*, typo3/sysext/reports/Tests/*, typo3/sysext/saltedpasswords/Tests/*, typo3/sysext/scheduler/Tests/*, typo3/sysext/impexp/Tests/*, typo3/sysext/workspaces/Tests/*]

    php_mess_detector:
        enabled: true
        config:
            code_size_rules: 
                cyclomatic_complexity: true
                npath_complexity: true
                excessive_method_length: false
                excessive_class_length: false
                excessive_parameter_list: false
                excessive_public_count: false
                too_many_fields: false
                too_many_methods: false
                excessive_class_complexity: false
            design_rules: 
                number_of_class_children: true
                depth_of_inheritance: true
                coupling_between_objects: true
            unused_code_rules: 
                unused_local_variable: true
                unused_private_method: true
                unused_formal_parameter: true
            naming_rules: 
                boolean_method_name: true
            controversial_rules: 
                camel_case_class_name: false
                camel_case_property_name: false
                camel_case_method_name: false
                camel_case_parameter_name: false
                camel_case_variable_name: false

    php_pdepend: true

    php_analyzer:
        enabled: false

    php_cpd:
        enabled: true
        excluded_dirs: [vendor/*, tests/*, Tests/*, app/*, bin/*, library/*, contrib/*, typo3/contrib/*, typo3/sysext/adodb/*, typo3/sysext/openid/lib/*, typo3/sysext/core/Tests/*, typo3/sysext/backend/Tests/*, typo3/sysext/frontend/Tests/*, typo3/sysext/belog/Tests/*, typo3/sysext/beuser/Tests/*, typo3/sysext/documentation/Tests/*, typo3/sysext/extbase/Tests/*, typo3/sysext/extensionmanager/Tests/*, typo3/sysext/felogin/Tests/*, typo3/sysext/fluid/Tests/*, typo3/sysext/form/Tests/*, typo3/sysext/indexed_search/Tests/*, typo3/sysext/install/Tests/*, typo3/sysext/lang/Tests/*, typo3/sysext/lowlevel/Tests/*, typo3/sysext/recordlist/Tests/*, typo3/sysext/reports/Tests/*, typo3/sysext/saltedpasswords/Tests/*, typo3/sysext/scheduler/Tests/*, typo3/sysext/impexp/Tests/*, typo3/sysext/workspaces/Tests/*]

    php_code_sniffer:
        enabled: false
        config:
            standard: TYPO3CMS

    php_hhvm:
        enabled: false

    external_code_coverage:
        enabled: true
        timeout: '2400'